### ISSUE TITLE
Code Example in tutorial parse greater than sign error 

### ISSUE THREAD

**Issue by pacozaa** [Urigo/angular-meteor#1331]
http://www.angular-meteor.com/tutorials/socially/angular1/search-sort-pagination-and-reactive-vars

enter this link and search for `&gt;` 

you will see the problem

I think it should be `>` instead of  `&gt;`

**Comment by Tallyb** [comment]
The functions are shown as =&gt instead of => 
The  components bindings are shown as '&lt' instead of '<'.

**Comment by kamilkisiela** [comment]
All the code is displayed by `mdg:tutorial-diff-box`

**Comment by 1zaak** [comment]
Yes, should be '<' instead of '&lt;'. I checked and the Angular version in the tutorial is in a different version than the latest one. So maybe it was an old Angular bug that was fixed now. But the tutorial should reflect that to make it easier for people going through it.

**Comment by kamilkisiela** [comment]
Urigo/angular-meteor-docs#74 should fix it

**Comment by pacozaa** [comment]
@kamilkisiela The problem still there.

http://www.angular-meteor.com/tutorials/socially/angular1/search-sort-pagination-and-reactive-vars

**Comment by kamilkisiela** [comment]
@pacozaa That PR hasn't been accepted yet :) Hold your horses, Mr. pacozaa! :smiley:
