### ISSUE TITLE
angular-templates 1.0.5 breaks using html files from local package in an app

### ISSUE THREAD

**Issue by Ben305** [Urigo/angular-meteor#1390]
After updating to angular-templates 1.0.5, imports from a local package won't work any longer. I have a meteor package that contains some directives and layout templates and I'm using in a Meteor 1.3.3 app.

I have created a sample repo that can be used to reproduce the issue. Check out
https://github.com/Ben305/AngularTemplatesSample and run it. You will see that the file `layout.html` from a local package file can be used without any problem.

Now run `meteor update angular-templates` and start the product again. In the browser console, you will see an error message:
<pre>packages/layout-package/layout.html - HTML template does not exists!</pre>

I'm using Angular-Meteor 1.3.11 with Meteor 1.3.4.1 (also tested with 1.3.4.4) running on OS X 10.11.4

**Comment by malaire** [comment]
Could this be the reason why ng-include doesn't work in Angular Meteor Tutorial?

https://github.com/Urigo/meteor-angular-socially/issues/123

**Comment by fpaboim** [comment]
I'm getting "HTML template does not exists!" too after upgrading. I was still using the old directive style of programming which was default a few months ago :P. Anyone have any ideas?

**Comment by davemecha** [comment]
I have a similar error and wonder if this might be the same or another bug.

In my code, I just imported templates with `import './template.html';`. 

Each template was wrapped in a `template` tag 

`<template id="testTemplate">[SOME TEMPLATE CODE]</template>`

And I referenced my template by it's id in the component definition:

    .component('myComponent', {
      templateUrl: 'testTemplate',
      controllerAs: 'vm',
      controller: MyController
    })

After the last update to angular-templates 1.0.5, I get an error in my browsers console, after some time:

`Error: only one instance of babel/polyfill is allowed`

I made a small showcase-setup for this on c9.io. I pinned `angular-templates@=1.0.5`

https://ide.c9.io/mechad/meteor-babel-showcase

When the version is switched to 1.0.3, the template is loaded correctly.

**Comment by kamilkisiela** [comment]
@davemecha @Ben305 Should be fixed by #1393

**Comment by Ben305** [comment]
@kamilkisiela I have another error when using the latest version from GitHub. I have updated my sample project so that you can reproduce the error
https://github.com/Ben305/AngularTemplatesSample

<pre>
=> Started MongoDB.                           
                                              
/Users/Ben/.meteor/packages/ecmascript/.0.4.8.j1oypv++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  sourcePath: 'layout.html',
  servePath: 'node_modules/meteor/layout-package/layout.html',
  installPath: 'node_modules/meteor/layout-package/layout.html',
  deps: { './layout.html!raw': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 6c 61 79 6f 75 74 2e 68 74 6d 6c 21 72 61 77 22 29 3b 0a>,
  hash: '37e0e7f0996adea967638eca758013022e2c1e9d' }
{ type: 'js',
  data: <Buffer 0a 20 20 20 20 20 20 69 66 20 28 4d 65 74 65 6f 72 2e 69 73 53 65 72 76 65 72 29 20 72 65 74 75 72 6e 3b 0a 0a 20 20 20 20 20 20 76 61 72 20 74 65 6d 70 ...>,
  sourcePath: 'layout.html',
  targetPath: 'layout.html',
  servePath: '/packages/layout-package/layout.html',
  hash: 'd2515b615bffb60c3e7827ef2ccd828b5a724f40',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'node_modules/meteor/layout-package/layout.html' }

    at checkProperty (/tools/isobuild/import-scanner.js:293:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:303:5)
    at /tools/isobuild/import-scanner.js:206:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:177:11)
    at /tools/isobuild/compiler-plugin.js:1011:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:982:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:926:8)
    at /tools/isobuild/bundler.js:697:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:688:18)
    at /tools/isobuild/bundler.js:2544:14
    at /tools/isobuild/bundler.js:2633:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Ben/.meteor/packages/meteor-tool/.1.3.5_1.1cz2par++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2632:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2525:31)
    at /tools/isobuild/bundler.js:2472:32
    at Object.withCache (/tools/fs/files.js:1445:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2472:16)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
</pre>

**Comment by blongstreth** [comment]
This bug is still showing up in angular-templates version 1.0.6_1 when used in a Meteor 1.2 stype application with local application packages.  Can this please be updated to work as Meteor 1.2 style application without NPM (meteor-node-stubs), imports, etc...for backwards compatibility?

```
=> Started proxy.                             
=> Started MongoDB.                           
/Users/foo/.meteor/packages/coffeescript/.1.1.4.hibsy4++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  sourcePath: 'client/loading-busy.html',
  servePath: 'node_modules/meteor/foo:loading/client/loading-busy.html',
  installPath: 'node_modules/meteor/foo:loading/client/loading-busy.html',
  deps: { './loading-busy.html!raw': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 6c 6f 61 64 69 6e 67 2d 62 75 73 79 2e 68 74 6d 6c 21 72 61 77 22 29 ...>,
  hash: '94fdda38ea14879da6923d3fcb3b73113aa065d3' }
{ type: 'js',
  data: <Buffer 0a 20 20 20 20 20 20 69 66 20 28 4d 65 74 65 6f 72 2e 69 73 53 65 72 76 65 72 29 20 72 65 74 75 72 6e 3b 0a 0a 20 20 20 20 20 20 76 61 72 20 74 65 6d 70 ...>,
  sourcePath: 'client/loading-busy.html',
  targetPath: 'client/loading-busy.html',
  servePath: '/packages/foo_loading/client/loading-busy.html',
  hash: '79cf7fef8e3eaaef87e49559b55741836a3eae79',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'node_modules/meteor/foo:loading/client/loading-busy.html' }

    at checkProperty (/tools/isobuild/import-scanner.js:293:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:303:5)
    at /tools/isobuild/import-scanner.js:206:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:177:11)
    at /tools/isobuild/compiler-plugin.js:1011:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:982:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:926:8)
    at /tools/isobuild/bundler.js:697:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:688:18)
    at /tools/isobuild/bundler.js:2544:14
    at /tools/isobuild/bundler.js:2633:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/foo/.meteor/packages/meteor-tool/.1.3.5_1.656zhu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2632:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2525:31)
    at /tools/isobuild/bundler.js:2472:32
    at Object.withCache (/tools/fs/files.js:1445:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2472:16)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by kamilkisiela** [comment]
@Ben305 knows but for others interested in, this has been fixed by #1397
