### ISSUE TITLE
Angular Meteor Website's body's padding-top cuts bottom content

### ISSUE THREAD

**Issue by Snesi** [Urigo/angular-meteor#1583]
<img width="514" alt="screen shot 2017-03-14 at 09 42 57" src="https://cloud.githubusercontent.com/assets/831197/23892441/e1da797a-089a-11e7-9993-e15e127fd677.png">

When you scroll to the bottom the content of the page is cut off because of the body's padding-top and overflow auto.

**Comment by Urigo** [comment]
fixed.
if not, please open a new issue

**Comment by Snesi** [comment]
Hi! @Urigo the issue is still there. If I have enough time after work I'll send you a PR. Is that ok? The fix is quite simple so it won't take much time.

**Comment by Urigo** [comment]
@Snesi yes it would be great to get a PR for that!
thank you so much!
https://github.com/urigo/angular-meteor-docs
