### ISSUE TITLE
npm link'ed packages are get compiled by angular-typescript-compiler

### ISSUE THREAD

**Issue by maxfriedmann** [Urigo/angular-meteor#1790]
Even though my tsconfig.json looks like this (copied from bare example)

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "declaration": false,
        "emitDecoratorMetadata": true,
        "importHelpers": true,
        "experimentalDecorators": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "es5",
        "skipLibCheck": true,
        "stripInternal": true,
        "noImplicitAny": false,
        "types": [
            "@types/meteor",
            "@types/mocha",
            "@types/chai",
            "@types/sinon"
        ]
    },
    "include": [
        "imports/**/*.ts",
        "client/**/*.ts",
        "server/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
``` 
the angular-typescript-compiler scans packages that were linked via `npm link`. 

This results to errors like
```
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (22, 14): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (23, 8): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (25, 4): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (50, 27): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (112, 24): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/jasmine/jasmine.ts (113, 4): Cannot find name 'jasmine'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/zone.ts (136, 11): Cannot redeclare block-scoped variable 'Zone'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/zone.ts (492, 6): Duplicate identifier 'HasTaskState'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/zone.ts (499, 6): Duplicate identifier 'TaskType'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/zone.ts (504, 6): Duplicate identifier 'TaskState'.
node_modules/@smallstack/meteor-client/node_modules/zone.js/lib/zone.ts (627, 7): Cannot redeclare block-scoped variable 'Zone'.
```

**Comment by ardatan** [comment]
Fixed in new version;
`meteor update --all-packages`

**Comment by maxfriedmann** [comment]
@ardatan This issue still occurs in the current version v0.2.9_2

**Comment by maxfriedmann** [comment]
```
[client]: TypeScript Files Compilation: 151367.038ms
[client]: HTML Files Compilation: 218.257ms  -
[client]: SCSS Files Compilation: 54.246ms   \
[server]: ES2015 modules Compilation: 2436.552ms
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/linq/observable/pairs.ts (28, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
  Type '[string, string]' is not assignable to type '[number, string]'.
    Type 'string' is not assignable to type 'number'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/linq/observable/pairs.ts (29, 5): Type 'Observable<[string, string]>' is not assignable to type 'Observable<[number, string]>'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es5.ts (3, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es5.ts (5, 17): Duplicate identifier 'ArrayLike'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es5.ts (8, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es6.ts (5, 17): Duplicate identifier 'ObservableOrPromise'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es6.ts (7, 17): Duplicate identifier 'ArrayLike'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es6.ts (10, 17): Duplicate identifier 'ArrayOrIterable'.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/es6.ts (20, 22): Interface 'IPromise<T>' cannot simultaneously extend types 'PromiseLike<T>' and 'Promise<T>'.
  Named property 'then' of types 'PromiseLike<T>' and 'Promise<T>' are not identical.
node_modules/@smallstack/server-meteor/node_modules/rx/ts/core/observer-extras.ts (65, 39): Property 'exception' does not exist on type 'Notification<number>'.
node_modules/@smallstack/server-meteor/src/workflows/conditions/ProbabilityCondition.ts (3, 30): Cannot find module '../types/models/WorkflowItem'.
node_modules/@smallstack/server-meteor/src/workflows/conditions/ProbabilityCondition.ts (4, 43): Cannot find module '../WorkflowConditionFunction'.
node_modules/@smallstack/server-meteor/src/workflows/conditions/ProbabilityCondition.ts (5, 33): Cannot find module '../WorkflowContext'.
node_modules/@smallstack/server-meteor/src/services/MeteorAuthService.ts (47, 13): Type 'Promise<void>' is not assignable to type 'Promise<string>'.
  Type 'void' is not assignable to type 'string'.
node_modules/@smallstack/server-meteor/src/services/MeteorCollectionAccessService.ts (41, 13): Type 'void' is not assignable to type 'PublisherMethodResult'.
[server]: TypeScript Files Compilation: 122461.488ms
```
