### ISSUE TITLE
Splicing an element of an array that is binded to an object in a collection

### ISSUE THREAD

**Issue by Cygnx** [Urigo/angular-meteor#689]
I'm currently trying to splice an array that is part of an object and am running into an error.

In my angular controller, I used the  $meteor.object call (with the default autoupdate param set to true )to get a cursor to an object that looks like this: 
{
'roomID': 1 , 
'users': [a,b,c,d,e,f,g,h,i]
}
now when the scope of this controller dies I want to remove element g from the users array. 
the code that I'm using to do this is: 

$scope.$on("$destroy", function() {
     object.users.splice(7,1);
}

However I'm running into this error:
![image](https://cloud.githubusercontent.com/assets/8177104/9928194/5e11d502-5cd9-11e5-94b6-361f0dfe8f04.png)

Any ideas why this is happening or perhaps a workaround?

**Comment by jonmc12** [comment]
+1, I have been seeing this as well since rc5.  For me mongo db on server is updating correctly, but minimongo is having issues on client and gives similar error in browser console.

**Comment by thomas-cabral** [comment]
Also running into this. If I push to the array there is no problem saving. It appears to be just when splicing and saving.

**Comment by Urigo** [comment]
OK so we are waiting for the pull request in Meteor to fix that.
Just a question, is downgrading to Meteor 1.1 resolve your problems?

**Comment by lanmower** [comment]
I could not figure out how to downgrade meteor

My meteorpad demonstration of the error does not seem to produce an error anymore
http://meteorpad.com/pad/5r9Xz4ceRFaXfBgLb/Array-Error
It does however still produce the error for me with my local software (on the updated meteor)

**Comment by Urigo** [comment]
Yes it looks like it changed Meteor 1.2.
Have you try to see if the pull request fixes that for you?

**Comment by lanmower** [comment]
Do you mean is my angular-meteor updated?

I'm currently running 1.0.0-rc.11

**Comment by Urigo** [comment]
@Cygnx could you please try again, this time with the new Meteor 1.2.0.2?

**Comment by thomas-cabral** [comment]
Didn't spend a bunch of time retesting, but with meteor 1.2.0.2 I am getting this "update failed: MongoError: Cannot update 'members.0' and 'members' at the same time undefined". Don't know if that is a my code problem or if this error has renamed itself :P.

I can still add items to the array, still just deleting that is causing the error.

NOTE: I did try creating a brand new object and got the same error.

**Comment by Urigo** [comment]
@thomas-cabral can you please share a reproduction?

**Comment by thomas-cabral** [comment]
Below is what I am using, addMember works fine removeMember does not. I have not tried to change anything since I ran into the first error (I have just been living with it). So there is a chance my remove method is simply not valid. I can mess around with removeMember in the morning and see if I can get somewhere.

$scope.project = $scope.$meteorObject(Projects, $stateParams.id).subscribe('projects');

$scope.addMember = function(user) {
            if (!$scope.project.members) {
                $scope.project.members = [];
                $scope.project.members.push(user)
            }
            else if ($scope.project.members.indexOf(user) != -1) {
                console.log("already added")
            }
            else {
                $scope.project.members.push(user)
            }
        };

$scope.removeMember = function(user) {
            $scope.project.members.splice($scope.project.members.indexOf(user), 1)
        };

**Comment by Urigo** [comment]
@jonmc12 has the new version fixed that for you?

**Comment by thomas-cabral** [comment]
Just a quick update, I am still getting the same error. Using "$scope.project.members = [];" in place of the splice gives the same error "update failed: MongoError: Cannot update 'members.0' and 'members' at the same time undefined".

**Comment by jonmc12** [comment]
@Urigo I'm on ```angular@1.0.1``` and currently I can not reproduce the bug on any of my client-side ```splice``` methods, so this is definitely an improvement in my app.  I haven't seen the ```error: documentMatches...``` error recently, fortunately.

However, I am still seeing the ```update failed: MongoError: Cannot update 'member_ids.0' and 'member_ids' at the same time``` error in a case where I call a server-side method that updates the collection with the following modifier:

```javascript 
{ '$pull': { member_ids: 'nvcuCkRuZFGT5KNzB' }, '$set': { updated_at: 1443638313945 } }
```

In the client, when I listen on ```Meteor.connection._stream``` this server-side update sends the following message to the client:

```javascript
{
  collection: "parties",
  fields: Object,
  updated_at: 1443638313945,
  member_ids: Array[0],
  length: 0,
  __proto__: Array[0],
  __proto__: Object,
  id: "5cbepr4hxjEGr7D5W",
  msg: "changed",
}
```

And, immediately after, I get the ```update failed``` error message above.

**Comment by Urigo** [comment]
Could you please check if the new pull request fixed the problem for you?

**Comment by jonmc12** [comment]
For me, yes, appears fixed.  Thx @netanelgilad

**Comment by Urigo** [comment]
Fixed in 1.0.2

**Comment by EyalRonel** [comment]
this post is a life saver ;) thanks!

**Comment by otporsad** [comment]
Hello, i have meteor angular 1.0.3 package and still have a problem with update. I have a $meteor.object. Then i try to remove an array element with splice. When i do .save() error appears:
update failed: MongoError: Cannot update 'treatments.6' and 'treatments' at the same time. Meteor version is: 1.2.1.

**Comment by Urigo** [comment]
@otporsad can you please test it out with the new 1.0.4 version?

**Comment by otporsad** [comment]
I did not have time for a detailed testing, but so far when i splice array item there is now a null instead of spliced element.
Something like this:
    [Item1, Item2,null,null,null]

**Comment by Urigo** [comment]
@otporsad this is strange, I've tested it again and it seems to work.
Can you share a repo with the problem?

**Comment by otporsad** [comment]
Hello, i made a new repo (I am new at this so i replicated, updated to 1.0.4 and adapted this repo: https://github.com/MarkPhillips7/angular-meteor-issue-793) to test this specific issue and now it works fine. Because of that i think my initial problem with null elements is caused by something else. Sorry for the confusion and thank you.

**Comment by Urigo** [comment]
@otporsad so just to make sure - now it's working for you and there is no other problem?

**Comment by otporsad** [comment]
Yes, so far I do not have any problems concerning splice() and save().

**Comment by max2mx** [comment]
Encountered the same problem but with updating to the latest version it's resolved now.
